/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e2dfff",
        "on-secondary": "#ffffff",
        surface: "#f9f9ff",
        "surface-variant": "#dce2f3",
        "on-tertiary-fixed": "#2a1700",
        "primary-container": "#4f46e5",
        "on-background": "#151c27",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eefe",
        "on-tertiary": "#ffffff",
        outline: "#777587",
        "on-surface": "#151c27",
        "secondary-fixed": "#6ffbbe",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#0f0069",
        "on-error": "#ffffff",
        background: "#f9f9ff",
        "on-error-container": "#93000a",
        "surface-dim": "#d3daea",
        "tertiary-fixed": "#ffddb8",
        "on-surface-variant": "#464555",
        "surface-bright": "#f9f9ff",
        "inverse-on-surface": "#ebf1ff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        primary: "#3525cd",
        "on-primary-container": "#dad7ff",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        secondary: "#006c49",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#885500",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-container": "#00714d",
        tertiary: "#684000",
        "surface-container-high": "#e2e8f8",
        "on-tertiary-container": "#ffd4a4",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#3323cc",
        "inverse-primary": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "secondary-container": "#6cf8bb",
        "surface-container-highest": "#dce2f3",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2a313d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        unit: "4px",
        "margin-desktop": "32px",
        lg: "24px",
        "sidebar-width": "260px",
        gutter: "24px",
        xs: "4px",
        "margin-mobile": "16px",
        md: "16px",
        xl: "32px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
      },
      fontSize: {
        "stats-number": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-sm": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
